/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedSalesRouteImport } from './routes/_authenticated/sales'
import { Route as AuthenticatedPurchasesRouteImport } from './routes/_authenticated/purchases'
import { Route as AuthenticatedProfitLossRouteImport } from './routes/_authenticated/profit-loss'
import { Route as AuthenticatedProductsRouteImport } from './routes/_authenticated/products'
import { Route as AuthenticatedHelpRouteImport } from './routes/_authenticated/help'
import { Route as AuthenticatedExpensesRouteImport } from './routes/_authenticated/expenses'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedCustomersRouteImport } from './routes/_authenticated/customers'
import { Route as AuthenticatedCurrentPackageRouteImport } from './routes/_authenticated/current-package'
import { Route as AuthenticatedBuyMessagesRouteImport } from './routes/_authenticated/buy-messages'
import { Route as AuthenticatedBackupRestoreRouteImport } from './routes/_authenticated/backup-restore'
import { Route as AuthenticatedAdminPaymentsRouteImport } from './routes/_authenticated/admin-payments'
import { Route as ApiPublicHooksDailyBackupRouteImport } from './routes/api/public/hooks/daily-backup'
import { Route as ApiPublicGoogleCallbackRouteImport } from './routes/api/public/google/callback'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSalesRoute = AuthenticatedSalesRouteImport.update({
  id: '/sales',
  path: '/sales',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPurchasesRoute = AuthenticatedPurchasesRouteImport.update({
  id: '/purchases',
  path: '/purchases',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProfitLossRoute = AuthenticatedProfitLossRouteImport.update({
  id: '/profit-loss',
  path: '/profit-loss',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProductsRoute = AuthenticatedProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedHelpRoute = AuthenticatedHelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedExpensesRoute = AuthenticatedExpensesRouteImport.update({
  id: '/expenses',
  path: '/expenses',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCustomersRoute = AuthenticatedCustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCurrentPackageRoute =
  AuthenticatedCurrentPackageRouteImport.update({
    id: '/current-package',
    path: '/current-package',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedBuyMessagesRoute =
  AuthenticatedBuyMessagesRouteImport.update({
    id: '/buy-messages',
    path: '/buy-messages',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedBackupRestoreRoute =
  AuthenticatedBackupRestoreRouteImport.update({
    id: '/backup-restore',
    path: '/backup-restore',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminPaymentsRoute =
  AuthenticatedAdminPaymentsRouteImport.update({
    id: '/admin-payments',
    path: '/admin-payments',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const ApiPublicHooksDailyBackupRoute =
  ApiPublicHooksDailyBackupRouteImport.update({
    id: '/api/public/hooks/daily-backup',
    path: '/api/public/hooks/daily-backup',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicGoogleCallbackRoute = ApiPublicGoogleCallbackRouteImport.update({
  id: '/api/public/google/callback',
  path: '/api/public/google/callback',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/admin-payments': typeof AuthenticatedAdminPaymentsRoute
  '/backup-restore': typeof AuthenticatedBackupRestoreRoute
  '/buy-messages': typeof AuthenticatedBuyMessagesRoute
  '/current-package': typeof AuthenticatedCurrentPackageRoute
  '/customers': typeof AuthenticatedCustomersRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/expenses': typeof AuthenticatedExpensesRoute
  '/help': typeof AuthenticatedHelpRoute
  '/products': typeof AuthenticatedProductsRoute
  '/profit-loss': typeof AuthenticatedProfitLossRoute
  '/purchases': typeof AuthenticatedPurchasesRoute
  '/sales': typeof AuthenticatedSalesRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/api/public/google/callback': typeof ApiPublicGoogleCallbackRoute
  '/api/public/hooks/daily-backup': typeof ApiPublicHooksDailyBackupRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/admin-payments': typeof AuthenticatedAdminPaymentsRoute
  '/backup-restore': typeof AuthenticatedBackupRestoreRoute
  '/buy-messages': typeof AuthenticatedBuyMessagesRoute
  '/current-package': typeof AuthenticatedCurrentPackageRoute
  '/customers': typeof AuthenticatedCustomersRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/expenses': typeof AuthenticatedExpensesRoute
  '/help': typeof AuthenticatedHelpRoute
  '/products': typeof AuthenticatedProductsRoute
  '/profit-loss': typeof AuthenticatedProfitLossRoute
  '/purchases': typeof AuthenticatedPurchasesRoute
  '/sales': typeof AuthenticatedSalesRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/api/public/google/callback': typeof ApiPublicGoogleCallbackRoute
  '/api/public/hooks/daily-backup': typeof ApiPublicHooksDailyBackupRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/admin-payments': typeof AuthenticatedAdminPaymentsRoute
  '/_authenticated/backup-restore': typeof AuthenticatedBackupRestoreRoute
  '/_authenticated/buy-messages': typeof AuthenticatedBuyMessagesRoute
  '/_authenticated/current-package': typeof AuthenticatedCurrentPackageRoute
  '/_authenticated/customers': typeof AuthenticatedCustomersRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/expenses': typeof AuthenticatedExpensesRoute
  '/_authenticated/help': typeof AuthenticatedHelpRoute
  '/_authenticated/products': typeof AuthenticatedProductsRoute
  '/_authenticated/profit-loss': typeof AuthenticatedProfitLossRoute
  '/_authenticated/purchases': typeof AuthenticatedPurchasesRoute
  '/_authenticated/sales': typeof AuthenticatedSalesRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/api/public/google/callback': typeof ApiPublicGoogleCallbackRoute
  '/api/public/hooks/daily-backup': typeof ApiPublicHooksDailyBackupRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/admin-payments'
    | '/backup-restore'
    | '/buy-messages'
    | '/current-package'
    | '/customers'
    | '/dashboard'
    | '/expenses'
    | '/help'
    | '/products'
    | '/profit-loss'
    | '/purchases'
    | '/sales'
    | '/settings'
    | '/api/public/google/callback'
    | '/api/public/hooks/daily-backup'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/admin-payments'
    | '/backup-restore'
    | '/buy-messages'
    | '/current-package'
    | '/customers'
    | '/dashboard'
    | '/expenses'
    | '/help'
    | '/products'
    | '/profit-loss'
    | '/purchases'
    | '/sales'
    | '/settings'
    | '/api/public/google/callback'
    | '/api/public/hooks/daily-backup'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/admin-payments'
    | '/_authenticated/backup-restore'
    | '/_authenticated/buy-messages'
    | '/_authenticated/current-package'
    | '/_authenticated/customers'
    | '/_authenticated/dashboard'
    | '/_authenticated/expenses'
    | '/_authenticated/help'
    | '/_authenticated/products'
    | '/_authenticated/profit-loss'
    | '/_authenticated/purchases'
    | '/_authenticated/sales'
    | '/_authenticated/settings'
    | '/api/public/google/callback'
    | '/api/public/hooks/daily-backup'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ApiPublicGoogleCallbackRoute: typeof ApiPublicGoogleCallbackRoute
  ApiPublicHooksDailyBackupRoute: typeof ApiPublicHooksDailyBackupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/sales': {
      id: '/_authenticated/sales'
      path: '/sales'
      fullPath: '/sales'
      preLoaderRoute: typeof AuthenticatedSalesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/purchases': {
      id: '/_authenticated/purchases'
      path: '/purchases'
      fullPath: '/purchases'
      preLoaderRoute: typeof AuthenticatedPurchasesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/profit-loss': {
      id: '/_authenticated/profit-loss'
      path: '/profit-loss'
      fullPath: '/profit-loss'
      preLoaderRoute: typeof AuthenticatedProfitLossRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/products': {
      id: '/_authenticated/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof AuthenticatedProductsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/help': {
      id: '/_authenticated/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof AuthenticatedHelpRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/expenses': {
      id: '/_authenticated/expenses'
      path: '/expenses'
      fullPath: '/expenses'
      preLoaderRoute: typeof AuthenticatedExpensesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/customers': {
      id: '/_authenticated/customers'
      path: '/customers'
      fullPath: '/customers'
      preLoaderRoute: typeof AuthenticatedCustomersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/current-package': {
      id: '/_authenticated/current-package'
      path: '/current-package'
      fullPath: '/current-package'
      preLoaderRoute: typeof AuthenticatedCurrentPackageRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/buy-messages': {
      id: '/_authenticated/buy-messages'
      path: '/buy-messages'
      fullPath: '/buy-messages'
      preLoaderRoute: typeof AuthenticatedBuyMessagesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/backup-restore': {
      id: '/_authenticated/backup-restore'
      path: '/backup-restore'
      fullPath: '/backup-restore'
      preLoaderRoute: typeof AuthenticatedBackupRestoreRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin-payments': {
      id: '/_authenticated/admin-payments'
      path: '/admin-payments'
      fullPath: '/admin-payments'
      preLoaderRoute: typeof AuthenticatedAdminPaymentsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/hooks/daily-backup': {
      id: '/api/public/hooks/daily-backup'
      path: '/api/public/hooks/daily-backup'
      fullPath: '/api/public/hooks/daily-backup'
      preLoaderRoute: typeof ApiPublicHooksDailyBackupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/google/callback': {
      id: '/api/public/google/callback'
      path: '/api/public/google/callback'
      fullPath: '/api/public/google/callback'
      preLoaderRoute: typeof ApiPublicGoogleCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminPaymentsRoute: typeof AuthenticatedAdminPaymentsRoute
  AuthenticatedBackupRestoreRoute: typeof AuthenticatedBackupRestoreRoute
  AuthenticatedBuyMessagesRoute: typeof AuthenticatedBuyMessagesRoute
  AuthenticatedCurrentPackageRoute: typeof AuthenticatedCurrentPackageRoute
  AuthenticatedCustomersRoute: typeof AuthenticatedCustomersRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedExpensesRoute: typeof AuthenticatedExpensesRoute
  AuthenticatedHelpRoute: typeof AuthenticatedHelpRoute
  AuthenticatedProductsRoute: typeof AuthenticatedProductsRoute
  AuthenticatedProfitLossRoute: typeof AuthenticatedProfitLossRoute
  AuthenticatedPurchasesRoute: typeof AuthenticatedPurchasesRoute
  AuthenticatedSalesRoute: typeof AuthenticatedSalesRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminPaymentsRoute: AuthenticatedAdminPaymentsRoute,
  AuthenticatedBackupRestoreRoute: AuthenticatedBackupRestoreRoute,
  AuthenticatedBuyMessagesRoute: AuthenticatedBuyMessagesRoute,
  AuthenticatedCurrentPackageRoute: AuthenticatedCurrentPackageRoute,
  AuthenticatedCustomersRoute: AuthenticatedCustomersRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedExpensesRoute: AuthenticatedExpensesRoute,
  AuthenticatedHelpRoute: AuthenticatedHelpRoute,
  AuthenticatedProductsRoute: AuthenticatedProductsRoute,
  AuthenticatedProfitLossRoute: AuthenticatedProfitLossRoute,
  AuthenticatedPurchasesRoute: AuthenticatedPurchasesRoute,
  AuthenticatedSalesRoute: AuthenticatedSalesRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ApiPublicGoogleCallbackRoute: ApiPublicGoogleCallbackRoute,
  ApiPublicHooksDailyBackupRoute: ApiPublicHooksDailyBackupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
