
ALTER TABLE public.expenses
  ADD COLUMN IF NOT EXISTS party_name TEXT NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS party_type TEXT NOT NULL DEFAULT 'customer',
  ADD COLUMN IF NOT EXISTS paid_amount NUMERIC NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS due_date DATE;
